language: cpp
script:
  - make
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
           - ubuntu-toolchain-r-test
          packages:
            - g++-4
            - libzip-dev
            - libsdl1.2-dev
            - libsdl-image1.2-dev
            - libcurl4-openssl-dev
            - zlib1g-dev
    - os: linux
      addons:
        apt:
          sources:
           - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - libzip-dev
            - libsdl1.2-dev
            - libsdl-image1.2-dev
            - libcurl4-openssl-dev
            - zlib1g-dev
    - os: linux
      addons:
        apt:
          sources:
           - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - libzip-dev
            - libsdl1.2-dev
            - libsdl-image1.2-dev
            - libcurl4-openssl-dev
            - zlib1g-dev
    - os: linux
      addons:
        apt:
          sources:
           - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libzip-dev
            - libsdl1.2-dev
            - libsdl-image1.2-dev
            - libcurl4-openssl-dev
            - zlib1g-dev
    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
           - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - libzip-dev
            - libsdl1.2-dev
            - libsdl-image1.2-dev
            - libcurl4-openssl-dev
            - zlib1g-dev
before_install:
  - eval "${MATRIX_EVAL}"
